"""add book_genre model

Revision ID: 859e6d0a23de
Revises: 259d3538b2f6
Create Date: 2025-05-06 21:29:44.114610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '859e6d0a23de'
down_revision = '259d3538b2f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_genre',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'genre_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_genre')
    # ### end Alembic commands ###
